export const FETCH_LEVELS = 'FETCH_LEVELS';
export const REQUESTED_LEVELS = 'REQUESTED_LEVELS';
export const REQUESTED_LEVELS_SUCCEEDED = 'REQUESTED_LEVELS_SUCCEEDED';
export const REQUESTED_LEVELS_FAILED = 'REQUESTED_LEVELS_FAILED';

export const ADD_TO_SCORE = 'ADD_TO_SCORE';

export const RESET = 'RESET';